### PR TITLE
Filter unsupported fields

### LINKED ISSUE #178: Handle SPIRE Server's that don't support hint/jwt-svid-ttl
The hint and jwt-svid-ttl fields are fairly new additions to the Entry SPIRE Server API. Therefore, when running against an older SPIRE server, these fields get ignored. The controller currently tries to update entries with these fields every reconciliation loop since the hint/jwt-svid-ttl fields were not retained.

We need to decide what do to here. A few options:
1. Crash if SPIRE server does not support all of the fields
2. Ignore fields not supported by SPIRE server for reconciliation

(1) is ideal, except that we then have to come up with a support SPIRE server matrix, and we have the potential to disrupt existing deployments. Another point to consider is that hint and jwt-svid-ttl fields are not commonly set. It might be a shame to force everyone to upgrade SPIRE server for no (perceived) benefit.
(2) has the downside of an operator being potentially confused why those fields aren't being honored.

### PR DESCRIPTION
**Pull request by MarcosDY**
Get the list of unsupported fields from configured spire server evert 10 minutes

fixes #178

### CODE REVIEW

File: pkg/spireapi/entryapi.go [hunk 1]
```diff
@@ -18,17 +18,32 @@ package spireapi
...
+	"fmt"
 
 	entryv1 "github.com/spiffe/spire-api-sdk/proto/spire/api/server/entry/v1"
+	"github.com/spiffe/spire-api-sdk/proto/spire/api/types"
 	apitypes "github.com/spiffe/spire-api-sdk/proto/spire/api/types"
 	"google.golang.org/grpc"
+	"google.golang.org/grpc/codes"
+	"sigs.k8s.io/controller-runtime/pkg/log"
+)
+
```
Comment (azdagron) [inline pkg/spireapi/entryapi.go:30]: nit: make a type for better compiler safety `type Field string` then use that in GetUnsupportedFields and the other code

File: pkg/spireapi/entryapi.go [hunk 2]
```diff
@@ -59,6 +74,65 @@ func (c entryClient) ListEntries(ctx context.Context) ([]Entry, error) {
...
 }
 
+func (c entryClient) GetUnsupportedFields(ctx context.Context, td string) (map[string]struct{}, error) {
+	unsupportedFields := make(map[string]struct{})
+	resp, err := c.api.BatchCreateEntry(ctx, &entryv1.BatchCreateEntryRequest{
+		Entries: []*apitypes.Entry{
+			{
+				ParentId: &types.SPIFFEID{
+					TrustDomain: td,
+					Path:        "/dummyagent",
```
Comment (azdagron) [inline pkg/spireapi/entryapi.go:84]:
```suggestion
					Path:        "/spire-controller-manager/unsupported-fields-test",
```

File: pkg/spireapi/entryapi.go [hunk 3]
```diff
@@ -59,6 +74,65 @@ func (c entryClient) ListEntries(ctx context.Context) ([]Entry, error) {
...
+				},
+				SpiffeId: &types.SPIFFEID{
+					TrustDomain: td,
+					Path:        "/w1",
```
Comment (azdagron) [inline pkg/spireapi/entryapi.go:88]:
```suggestion
					Path:        "/spire-controller-manager/unsupported-fields-test",
```

File: pkg/spireapi/entryapi.go [hunk 4]
```diff
@@ -59,6 +74,65 @@ func (c entryClient) ListEntries(ctx context.Context) ([]Entry, error) {
 	return entriesFromAPI(entries)
 }
 
+func (c entryClient) GetUnsupportedFields(ctx context.Context, td string) (map[string]struct{}, error) {
+	unsupportedFields := make(map[string]struct{})
```
Comment (azdagron) [inline pkg/spireapi/entryapi.go:78]: nit: move this down closer to point-of-use

File: pkg/spireapi/entryapi_test.go [hunk 5]
```diff
@@ -309,6 +367,8 @@ type entryServer struct {
 	mtx     sync.RWMutex
 	entries []*apitypes.Entry
 
+	cleanUnsupportedFields bool
```
Comment (azdagron) [inline pkg/spireapi/entryapi_test.go:370]: nit: clear?

File: pkg/spireentry/reconciler.go [hunk 6]
```diff
@@ -67,11 +69,19 @@ func Reconciler(config ReconcilerConfig) reconciler.Reconciler {
...
+
+	unsupportedFields        map[string]struct{}
+	nextGetUnsupportedFields time.Time
 }
 
 func (r *entryReconciler) reconcile(ctx context.Context) {
 	log := log.FromContext(ctx)
 
+	if time.Now().After(r.nextGetUnsupportedFields) {
+		r.recalculateUnsupportField(ctx, log)
```
Comment (azdagron) [inline pkg/spireentry/reconciler.go:81]:
```suggestion
		r.recalculateUnsupportFields(ctx, log)
```

File: pkg/spireentry/reconciler.go [hunk 7]
```diff
@@ -179,11 +189,34 @@ func (r *entryReconciler) reconcile(ctx context.Context) {
...
+		log.Error(err, "failed to get unsupported fields")
+		return
+	}
+
+	if len(unsupportedFields) > 0 {
+		var fields []string
+		for key := range unsupportedFields {
+			fields = append(fields, key)
+		}
+		log.Info("SPIRE Server version does not support fields", "keys", strings.Join(fields, ","))
```
Comment (azdagron) [inline pkg/spireentry/reconciler.go:204]: This doesn't need to happen now, but it might be nice to track old and new and then only log what changes.
